# Maintainer: Andrés Merlo Trujillo <a.merlo.truji10@gmail.com>
pkgname=dasik
pkgver=0.5.0
pkgrel=1
pkgdesc="Declarative Arch Linux installer: describe the target system in one JSON file and converge to it"
arch=('any')
url="https://github.com/amt911/dasik"
license=('MIT')
depends=('python' 'python-pydantic' 'python-colorama')
makedepends=('git' 'python-build' 'python-installer' 'python-wheel' 'python-setuptools')
# dasik shells out to real system tooling. None of it is needed to parse a
# config or to run `dasik check`, so none of it is a hard dependency; each one
# is only reached by the domain that uses it, and a missing binary raises
# CommandNotFoundException with the name in it.
optdepends=('arch-install-scripts: pacstrap/arch-chroot/genfstab — required to install onto a target'
            'gptfdisk: sgdisk — required for disk partitioning'
            'dosfstools: mkfs.fat for the ESP'
            'e2fsprogs: mkfs.ext4'
            'btrfs-progs: btrfs subvolume layouts'
            'cryptsetup: LUKS encryption and pendrive unlock'
            'sudo: builds packages from the AUR / a Git PKGBUILD as an unprivileged user')
# GitHub's autogenerated tag tarballs are NOT byte-stable (the same tag has
# produced different archives over time), so a committed sha256 can rot on its
# own. The tag is the anchor instead — the conventional pairing for a VCS
# source pinned to a tag. `scripts/bump.sh` is the only thing that edits pkgver.
source=("$pkgname::git+$url.git#tag=$pkgver")
sha256sums=('SKIP')

build() {
    cd "$srcdir/$pkgname"
    # --no-isolation: build against the packaged python-setuptools/wheel rather
    # than letting `build` create a venv and pull them from PyPI mid-makepkg.
    python -m build --wheel --no-isolation
}

check() {
    cd "$srcdir/$pkgname"
    # The unit suite needs the [dev] extra (pytest/hypothesis), which is not a
    # makedepend; a syntax-level compile is what can be asserted offline here.
    # The real gates live in the upstream repo's CI and pre-push hook.
    python -m compileall -q dasik > /dev/null
}

package() {
    cd "$srcdir/$pkgname"
    python -m installer --destdir="$pkgdir" dist/*.whl

    install -Dm644 README.md "$pkgdir/usr/share/doc/$pkgname/README.md"
    install -Dm644 docs/config-reference.md "$pkgdir/usr/share/doc/$pkgname/config-reference.md"

    # The sample configs. On a live ISO these are the quickest way to get a
    # working config in front of you without cloning the source tree.
    install -d "$pkgdir/usr/share/$pkgname/examples"
    cp -r config/. "$pkgdir/usr/share/$pkgname/examples/"
    find "$pkgdir/usr/share/$pkgname/examples" -type f -exec chmod 644 {} \;
    find "$pkgdir/usr/share/$pkgname/examples" -type d -exec chmod 755 {} \;

    # NOTE: upstream declares MIT in pyproject.toml but ships no LICENSE file,
    # so there is no license text to install (Arch requires it for MIT). Once
    # https://github.com/amt911/dasik grows one, add:
    #   install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
